version: '3.8'

services:
  geometry-jump:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        VERSION: ${VERSION:-latest}
    image: geometry-jump:${VERSION:-latest}
    container_name: geometry-jump-game
    restart: unless-stopped
    ports:
      - "8080:80"
    labels:
      # Traefik labels for reverse proxy
      - "traefik.enable=true"
      - "traefik.http.routers.geometry-jump.rule=Host(`geometry.local`) || Host(`geometry.yourdomain.com`)"
      - "traefik.http.routers.geometry-jump.entrypoints=web"
      - "traefik.http.services.geometry-jump.loadbalancer.server.port=80"
      # Optional: Enable HTTPS with Let's Encrypt
      - "traefik.http.routers.geometry-jump-secure.rule=Host(`geometry.local`) || Host(`geometry.yourdomain.com`)"
      - "traefik.http.routers.geometry-jump-secure.entrypoints=websecure"
      - "traefik.http.routers.geometry-jump-secure.tls.certresolver=myresolver"
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx

  # Optional: Include Traefik if not already running
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Optional: Let's Encrypt configuration
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
    # If network doesn't exist, create it with:
    # docker network create traefik-network
