version: '3.8'

services:
  geometry-jump:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        VERSION: ${VERSION:-latest}
    image: geometry-jump:${VERSION:-latest}
    container_name: geometry-jump-game
    restart: unless-stopped
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
